- name: Drain nodes
  command: kubectl drain {{ item }} --delete-local-data --force --ignore-daemonsets
  with_items:
    - worker1
    - worker2
    - kubemaster
  ignore_errors: true

- name: Delete nodes
  command: kubectl delete node {{ item }}
  with_items:
    - worker1
    - worker2
    - kubemaster
  ignore_errors: true

- name: Reset kubeadm installed state
  command: kubeadm reset
  become: yes
